#!/bin/bash
set -e

# ─────────────────────────────────────────────────────────────────────────────
# Powder Roster — Install Script
# Tested on Debian 11/12 and Ubuntu 22.04 LXC containers
# Run as root:  bash install.sh
# ─────────────────────────────────────────────────────────────────────────────

REPO_URL="https://github.com/alreadyded1/Powder-Roster.git"
INSTALL_DIR="/opt/powder-roster"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && die "Please run as root (sudo bash install.sh)"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════╗${NC}"
echo -e "${CYAN}║       Powder Roster Installer        ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════╝${NC}"
echo ""

# ── Install Docker if missing ─────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    info "Docker not found — installing..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release && echo "$ID")/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/$(. /etc/os-release && echo "$ID") \
$(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
    systemctl enable --now docker
    success "Docker installed"
else
    success "Docker already installed ($(docker --version | cut -d' ' -f3 | tr -d ','))"
fi

# ── Install git if missing ────────────────────────────────────────────────────
if ! command -v git &>/dev/null; then
    info "Installing git..."
    apt-get install -y -qq git
fi

# ── Clone or update repo ──────────────────────────────────────────────────────
if [[ -d "$INSTALL_DIR/.git" ]]; then
    warn "Directory $INSTALL_DIR already exists — run update.sh instead."
    exit 0
fi

info "Cloning repository to $INSTALL_DIR..."
git clone --quiet "$REPO_URL" "$INSTALL_DIR"
success "Repository cloned"

# ── Generate .env ─────────────────────────────────────────────────────────────
ENV_FILE="$INSTALL_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    SECRET=$(tr -dc 'A-Za-z0-9!@#$%^&*' </dev/urandom | head -c 48)
    cat > "$ENV_FILE" <<EOF
# Generated by install.sh — do not share this file
SECRET_KEY=${SECRET}
EOF
    chmod 600 "$ENV_FILE"
    success ".env created with a random SECRET_KEY"
else
    warn ".env already exists — skipping key generation"
fi

# ── Build and start ───────────────────────────────────────────────────────────
info "Building containers (this may take a few minutes)..."
cd "$INSTALL_DIR"
docker compose --env-file .env up -d --build

success "Powder Roster is running!"
echo ""

# ── Detect IP for access URL ──────────────────────────────────────────────────
HOST_IP=$(hostname -I | awk '{print $1}')
echo -e "  ${GREEN}App:${NC}     http://${HOST_IP}:3000"
echo -e "  ${GREEN}API:${NC}     http://${HOST_IP}:8000/docs"
echo -e "  ${GREEN}Login:${NC}   admin@example.com / changeme"
echo ""
echo -e "  ${YELLOW}Remember to change the admin password after first login!${NC}"
echo ""
echo -e "  To update later:  ${CYAN}bash $INSTALL_DIR/update.sh${NC}"
echo ""
